# Generated by Django 5.0.6 on 2024-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_review_guest_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover',
            field=models.ImageField(default='guesthouse_booking\\static\\images', upload_to='images/'),
            preserve_default=False,
        ),
    ]
